version: '3.2'
services:
  stream8:
    build:
      context: .
      dockerfile: Dockerfile.stream8
    image: ghcr.io/${{ github.repository }}:el8stream
  stream9:
    build:
      context: .
      dockerfile: Dockerfile.stream9
    image: ghcr.io/${{ github.repository }}:el9stream
