name: Build and Push
on:
  push:
    branches:
      - main
      - int-release
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch: 
    inputs:
      additional_packages:
        required: false
        type: string
jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Add manual packages
        if: ${{ github.event.inputs.additional_packages }}
        run: |
          echo "RUN dnf install -y ${{ github.event.inputs.additional_packages }} && dnf clean all" >> Dockerfile.stream8
          echo "RUN dnf install -y ${{ github.event.inputs.additional_packages }} && dnf clean all" >> Dockerfile.stream9
      - name: Build image
        run: docker-compose build
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push image
        run: docker-compose push
